### PR TITLE
Add styling to landing page header and search area

### PR DESCRIPTION
**Pull request by ScottyyyB**
## Description:
Add basic styling to the landing page, restaurant page and modify navbar

## What we learned:
* How to properly align an element to the right or left using float and making sure to use 'clear: both' on the parent container, also setting the position on an element to relative and using bottom or top for example, to tweak the position slightly. 

## Screenshot: 
screen shot 2018-01-17 at 12 03 04

### CODE REVIEW

**Comment by tochman** [comment]
Please make sure this is updated to hold the latest code and let us know if we can do a final review.

**Comment by ScottyyyB** [comment]
PR updated with the latest code.

**Comment by marizaswart** [comment]
LGTM :)

**Review by diraulo — APPROVED** [review]
Would've loved to see some Sass instead of CSS but not a big deal. You can go ahead and :shipit:

**Pull request merged**
